create table if not exists public.competition_applications (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  owner_email text not null,
  owner_name text,
  owner_phone text,
  participant_kind text not null default 'owner',
  participant_id text not null default 'owner',
  participant_snapshot jsonb not null default '{}'::jsonb,
  competition_slug text not null,
  competition_name text not null,
  stage_id text not null,
  stage_label text,
  competition_date_label text,
  competition_window_label text,
  registration_kind text not null default 'individual',
  payment_option_id text,
  payment_option_title text,
  team_name text,
  seed_time text,
  comment text,
  status text not null default 'submitted',
  admission_status text not null default 'pending',
  payment_status text not null default 'not_required',
  status_changed_at timestamptz not null default timezone('utc', now()),
  status_changed_by text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.competition_applications
  add column if not exists owner_email text;

alter table public.competition_applications
  add column if not exists owner_name text;

alter table public.competition_applications
  add column if not exists owner_phone text;

alter table public.competition_applications
  add column if not exists participant_snapshot jsonb not null default '{}'::jsonb;

alter table public.competition_applications
  add column if not exists admission_status text not null default 'pending';

alter table public.competition_applications
  add column if not exists payment_status text not null default 'not_required';

alter table public.competition_applications
  drop constraint if exists competition_applications_status_check;

alter table public.competition_applications
  add constraint competition_applications_status_check
  check (
    status in (
      'submitted',
      'reviewing',
      'needs_fix',
      'approved',
      'payment_pending',
      'paid',
      'admitted',
      'withdrawn',
      'rejected'
    )
  );

alter table public.competition_applications
  drop constraint if exists competition_applications_participant_kind_check;

alter table public.competition_applications
  add constraint competition_applications_participant_kind_check
  check (participant_kind in ('owner', 'athlete'));

alter table public.competition_applications
  drop constraint if exists competition_applications_registration_kind_check;

alter table public.competition_applications
  add constraint competition_applications_registration_kind_check
  check (registration_kind in ('individual', 'relay', 'long-distance'));

alter table public.competition_applications
  drop constraint if exists competition_applications_admission_status_check;

alter table public.competition_applications
  add constraint competition_applications_admission_status_check
  check (admission_status in ('pending', 'blocked', 'ready', 'admitted', 'rejected'));

alter table public.competition_applications
  drop constraint if exists competition_applications_payment_status_check;

alter table public.competition_applications
  add constraint competition_applications_payment_status_check
  check (payment_status in ('not_required', 'pending', 'paid', 'failed', 'refunded'));

create table if not exists public.competition_application_events (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.competition_applications (id) on delete cascade,
  from_status text,
  to_status text not null,
  actor_id uuid references auth.users (id) on delete set null,
  actor_role text,
  actor_name text,
  public_comment text,
  related_document_types text[] not null default array[]::text[],
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.competition_application_events
  drop constraint if exists competition_application_events_to_status_check;

alter table public.competition_application_events
  add constraint competition_application_events_to_status_check
  check (
    to_status in (
      'submitted',
      'reviewing',
      'needs_fix',
      'approved',
      'payment_pending',
      'paid',
      'admitted',
      'withdrawn',
      'rejected'
    )
  );

alter table public.competition_application_events
  drop constraint if exists competition_application_events_from_status_check;

alter table public.competition_application_events
  add constraint competition_application_events_from_status_check
  check (
    from_status is null
    or from_status in (
      'submitted',
      'reviewing',
      'needs_fix',
      'approved',
      'payment_pending',
      'paid',
      'admitted',
      'withdrawn',
      'rejected'
    )
  );

create or replace function public.touch_competition_application_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := timezone('utc', now());

  if new.status is distinct from old.status then
    new.status_changed_at := timezone('utc', now());
  end if;

  return new;
end;
$$;

drop trigger if exists competition_applications_touch_updated_at on public.competition_applications;
create trigger competition_applications_touch_updated_at
before update on public.competition_applications
for each row execute procedure public.touch_competition_application_updated_at();

create or replace function public.log_competition_application_status_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.competition_application_events (
      application_id,
      from_status,
      to_status,
      actor_id,
      actor_role,
      actor_name,
      public_comment,
      created_at
    )
    values (
      new.id,
      case when tg_op = 'INSERT' then null else old.status end,
      new.status,
      auth.uid(),
      public.current_crm_role(),
      new.status_changed_by,
      nullif(trim(coalesce(new.comment, '')), ''),
      coalesce(new.status_changed_at, timezone('utc', now()))
    );
  end if;

  return new;
end;
$$;

drop trigger if exists competition_applications_log_status_event on public.competition_applications;
create trigger competition_applications_log_status_event
after insert or update on public.competition_applications
for each row execute procedure public.log_competition_application_status_event();

revoke execute on function public.log_competition_application_status_event() from public, anon, authenticated;

create index if not exists competition_applications_owner_user_id_idx
  on public.competition_applications (owner_user_id);

create index if not exists competition_applications_stage_id_idx
  on public.competition_applications (stage_id);

create index if not exists competition_applications_status_idx
  on public.competition_applications (status);

create index if not exists competition_applications_updated_at_idx
  on public.competition_applications (updated_at desc);

create or replace function public.get_competition_stage_active_registration_count(target_stage_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer
  from public.competition_applications as application
  where application.stage_id = target_stage_id
    and application.status in (
      'submitted',
      'reviewing',
      'needs_fix',
      'approved',
      'payment_pending',
      'paid'
    );
$$;

grant execute on function public.get_competition_stage_active_registration_count(text) to authenticated;
revoke execute on function public.get_competition_stage_active_registration_count(text) from public, anon;

create index if not exists competition_applications_created_at_idx
  on public.competition_applications (created_at desc);

create index if not exists competition_applications_status_updated_at_idx
  on public.competition_applications (status, updated_at desc);

create index if not exists competition_applications_payment_status_updated_at_idx
  on public.competition_applications (payment_status, updated_at desc);

create index if not exists competition_application_events_application_id_idx
  on public.competition_application_events (application_id, created_at desc);

create index if not exists competition_application_events_actor_id_idx
  on public.competition_application_events (actor_id);

create or replace function public.search_competition_applications_for_admin(
  search_query text default '',
  status_filter text default 'all',
  payment_status_filter text default 'all',
  page_number integer default 1,
  page_size integer default 20
)
returns table (
  id uuid,
  owner_user_id uuid,
  owner_email text,
  owner_name text,
  owner_phone text,
  participant_kind text,
  participant_id text,
  participant_snapshot jsonb,
  competition_slug text,
  competition_name text,
  stage_id text,
  stage_label text,
  competition_date_label text,
  competition_window_label text,
  registration_kind text,
  payment_option_id text,
  payment_option_title text,
  team_name text,
  seed_time text,
  comment text,
  status text,
  admission_status text,
  payment_status text,
  status_changed_at timestamptz,
  status_changed_by text,
  created_at timestamptz,
  updated_at timestamptz,
  total_count bigint
)
language sql
stable
security invoker
set search_path = public
as $$
  with normalized_params as (
    select
      nullif(trim(coalesce(search_query, '')), '') as query,
      case
        when status_filter in (
          'submitted',
          'reviewing',
          'needs_fix',
          'approved',
          'payment_pending',
          'paid',
          'admitted',
          'withdrawn',
          'rejected'
        ) then status_filter
        else 'all'
      end as status,
      case
        when payment_status_filter in ('not_required', 'pending', 'paid', 'failed', 'refunded') then payment_status_filter
        else 'all'
      end as payment_status,
      greatest(coalesce(page_number, 1), 1) as page,
      least(greatest(coalesce(page_size, 20), 1), 100) as size
  ),
  filtered_applications as (
    select
      applications.*,
      count(*) over () as total_count
    from public.competition_applications as applications
    cross join normalized_params
    where public.current_crm_role() = 'admin'
      and (
        normalized_params.status = 'all'
        or applications.status = normalized_params.status
      )
      and (
        normalized_params.payment_status = 'all'
        or applications.payment_status = normalized_params.payment_status
      )
      and (
        normalized_params.query is null
        or concat_ws(
          ' ',
          applications.owner_email,
          applications.owner_name,
          applications.owner_phone,
          applications.competition_slug,
          applications.competition_name,
          applications.stage_id,
          applications.stage_label,
          applications.competition_date_label,
          applications.competition_window_label,
          applications.registration_kind,
          applications.payment_option_title,
          applications.team_name,
          applications.seed_time,
          applications.comment,
          applications.status,
          applications.payment_status,
          applications.participant_snapshot ->> 'name',
          applications.participant_snapshot ->> 'fullName',
          applications.participant_snapshot ->> 'club',
          applications.participant_snapshot ->> 'phone',
          applications.participant_snapshot ->> 'email'
        ) ilike '%' || normalized_params.query || '%'
      )
  )
  select
    filtered_applications.id,
    filtered_applications.owner_user_id,
    filtered_applications.owner_email,
    filtered_applications.owner_name,
    filtered_applications.owner_phone,
    filtered_applications.participant_kind,
    filtered_applications.participant_id,
    filtered_applications.participant_snapshot,
    filtered_applications.competition_slug,
    filtered_applications.competition_name,
    filtered_applications.stage_id,
    filtered_applications.stage_label,
    filtered_applications.competition_date_label,
    filtered_applications.competition_window_label,
    filtered_applications.registration_kind,
    filtered_applications.payment_option_id,
    filtered_applications.payment_option_title,
    filtered_applications.team_name,
    filtered_applications.seed_time,
    filtered_applications.comment,
    filtered_applications.status,
    filtered_applications.admission_status,
    filtered_applications.payment_status,
    filtered_applications.status_changed_at,
    filtered_applications.status_changed_by,
    filtered_applications.created_at,
    filtered_applications.updated_at,
    filtered_applications.total_count
  from filtered_applications
  order by filtered_applications.updated_at desc
  limit (select size from normalized_params)
  offset (select (page - 1) * size from normalized_params);
$$;

grant execute on function public.search_competition_applications_for_admin(text, text, text, integer, integer) to authenticated;
revoke execute on function public.search_competition_applications_for_admin(text, text, text, integer, integer) from public, anon;

alter table public.competition_applications enable row level security;
alter table public.competition_application_events enable row level security;

drop policy if exists "Allow authenticated users to insert own competition applications" on public.competition_applications;
drop policy if exists "Allow authenticated users to read own competition applications" on public.competition_applications;
drop policy if exists "Allow authenticated users to withdraw own competition applications" on public.competition_applications;
drop policy if exists "Allow admin read competition applications" on public.competition_applications;
drop policy if exists "Allow admin update competition applications" on public.competition_applications;
drop policy if exists "Allow admin delete competition applications" on public.competition_applications;
drop policy if exists "Allow authenticated users to delete own withdrawn competition applications" on public.competition_applications;

create policy "Allow authenticated users to insert own competition applications"
on public.competition_applications
for insert
to authenticated
with check (
  owner_user_id = auth.uid()
  and public.current_crm_role() = 'user'
  and nullif(trim(owner_email), '') is not null
  and nullif(trim(competition_slug), '') is not null
  and nullif(trim(competition_name), '') is not null
  and nullif(trim(stage_id), '') is not null
  and participant_kind in ('owner', 'athlete')
  and registration_kind in ('individual', 'relay', 'long-distance')
  and status = 'submitted'
);

create policy "Allow authenticated users to read own competition applications"
on public.competition_applications
for select
to authenticated
using (
  owner_user_id = auth.uid()
  or public.current_crm_role() = 'admin'
);

create policy "Allow authenticated users to withdraw own competition applications"
on public.competition_applications
for update
to authenticated
using (
  owner_user_id = auth.uid()
  and status in ('submitted', 'reviewing', 'needs_fix', 'approved', 'payment_pending')
)
with check (
  owner_user_id = auth.uid()
  and status = 'withdrawn'
);

create policy "Allow admin read competition applications"
on public.competition_applications
for select
to authenticated
using (public.current_crm_role() = 'admin');

create policy "Allow admin update competition applications"
on public.competition_applications
for update
to authenticated
using (public.current_crm_role() = 'admin')
with check (public.current_crm_role() = 'admin');

create policy "Allow admin delete competition applications"
on public.competition_applications
for delete
to authenticated
using (public.current_crm_role() = 'admin');

create policy "Allow authenticated users to delete own withdrawn competition applications"
on public.competition_applications
for delete
to authenticated
using (
  owner_user_id = auth.uid()
  and status = 'withdrawn'
);

drop policy if exists "Allow authenticated users to read own competition application events" on public.competition_application_events;
drop policy if exists "Allow admin read competition application events" on public.competition_application_events;

create policy "Allow authenticated users to read own competition application events"
on public.competition_application_events
for select
to authenticated
using (
  exists (
    select 1
    from public.competition_applications as competition_applications
    where competition_applications.id = competition_application_events.application_id
      and competition_applications.owner_user_id = auth.uid()
  )
  or public.current_crm_role() = 'admin'
);

create policy "Allow admin read competition application events"
on public.competition_application_events
for select
to authenticated
using (public.current_crm_role() = 'admin');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'competition_applications'
  ) then
    alter publication supabase_realtime add table public.competition_applications;
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'competition_application_events'
  ) then
    alter publication supabase_realtime add table public.competition_application_events;
  end if;
end;
$$;
