create table if not exists public.competition_applications (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  owner_email text not null,
  owner_name text,
  owner_phone text,
  participant_kind text not null default 'owner',
  participant_id text not null default 'owner',
  participant_snapshot jsonb not null default '{}'::jsonb,
  competition_slug text not null,
  competition_name text not null,
  stage_id text not null,
  stage_label text,
  competition_date_label text,
  competition_window_label text,
  registration_kind text not null default 'individual',
  payment_option_id text,
  payment_option_title text,
  team_name text,
  seed_time text,
  comment text,
  status text not null default 'submitted',
  admission_status text not null default 'pending',
  payment_status text not null default 'not_required',
  status_changed_at timestamptz not null default timezone('utc', now()),
  status_changed_by text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.competition_applications
  add column if not exists owner_email text;

alter table public.competition_applications
  add column if not exists owner_name text;

alter table public.competition_applications
  add column if not exists owner_phone text;

alter table public.competition_applications
  add column if not exists participant_snapshot jsonb not null default '{}'::jsonb;

alter table public.competition_applications
  add column if not exists admission_status text not null default 'pending';

alter table public.competition_applications
  add column if not exists payment_status text not null default 'not_required';

alter table public.competition_applications
  drop constraint if exists competition_applications_status_check;

alter table public.competition_applications
  add constraint competition_applications_status_check
  check (
    status in (
      'submitted',
      'reviewing',
      'needs_fix',
      'approved',
      'payment_pending',
      'paid',
      'admitted',
      'withdrawn',
      'rejected'
    )
  );

alter table public.competition_applications
  drop constraint if exists competition_applications_participant_kind_check;

alter table public.competition_applications
  add constraint competition_applications_participant_kind_check
  check (participant_kind in ('owner', 'athlete'));

alter table public.competition_applications
  drop constraint if exists competition_applications_registration_kind_check;

alter table public.competition_applications
  add constraint competition_applications_registration_kind_check
  check (registration_kind in ('individual', 'relay', 'long-distance'));

alter table public.competition_applications
  drop constraint if exists competition_applications_admission_status_check;

alter table public.competition_applications
  add constraint competition_applications_admission_status_check
  check (admission_status in ('pending', 'blocked', 'ready', 'admitted', 'rejected'));

alter table public.competition_applications
  drop constraint if exists competition_applications_payment_status_check;

alter table public.competition_applications
  add constraint competition_applications_payment_status_check
  check (payment_status in ('not_required', 'pending', 'paid', 'failed', 'refunded'));

create table if not exists public.competition_application_events (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.competition_applications (id) on delete cascade,
  from_status text,
  to_status text not null,
  actor_id uuid references auth.users (id) on delete set null,
  actor_role text,
  actor_name text,
  public_comment text,
  related_document_types text[] not null default array[]::text[],
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.competition_application_events
  drop constraint if exists competition_application_events_to_status_check;

alter table public.competition_application_events
  add constraint competition_application_events_to_status_check
  check (
    to_status in (
      'submitted',
      'reviewing',
      'needs_fix',
      'approved',
      'payment_pending',
      'paid',
      'admitted',
      'withdrawn',
      'rejected'
    )
  );

alter table public.competition_application_events
  drop constraint if exists competition_application_events_from_status_check;

alter table public.competition_application_events
  add constraint competition_application_events_from_status_check
  check (
    from_status is null
    or from_status in (
      'submitted',
      'reviewing',
      'needs_fix',
      'approved',
      'payment_pending',
      'paid',
      'admitted',
      'withdrawn',
      'rejected'
    )
  );

create or replace function public.touch_competition_application_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());

  if new.status is distinct from old.status then
    new.status_changed_at := timezone('utc', now());
  end if;

  return new;
end;
$$;

drop trigger if exists competition_applications_touch_updated_at on public.competition_applications;
create trigger competition_applications_touch_updated_at
before update on public.competition_applications
for each row execute procedure public.touch_competition_application_updated_at();

create or replace function public.log_competition_application_status_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.competition_application_events (
      application_id,
      from_status,
      to_status,
      actor_id,
      actor_role,
      actor_name,
      public_comment,
      created_at
    )
    values (
      new.id,
      case when tg_op = 'INSERT' then null else old.status end,
      new.status,
      auth.uid(),
      public.current_crm_role(),
      new.status_changed_by,
      nullif(trim(coalesce(new.comment, '')), ''),
      coalesce(new.status_changed_at, timezone('utc', now()))
    );
  end if;

  return new;
end;
$$;

drop trigger if exists competition_applications_log_status_event on public.competition_applications;
create trigger competition_applications_log_status_event
after insert or update on public.competition_applications
for each row execute procedure public.log_competition_application_status_event();

create index if not exists competition_applications_owner_user_id_idx
  on public.competition_applications (owner_user_id);

create index if not exists competition_applications_stage_id_idx
  on public.competition_applications (stage_id);

create index if not exists competition_applications_status_idx
  on public.competition_applications (status);

create index if not exists competition_applications_updated_at_idx
  on public.competition_applications (updated_at desc);

create or replace function public.get_competition_stage_active_registration_count(target_stage_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer
  from public.competition_applications as application
  where application.stage_id = target_stage_id
    and application.status in (
      'submitted',
      'reviewing',
      'needs_fix',
      'approved',
      'payment_pending',
      'paid'
    );
$$;

grant execute on function public.get_competition_stage_active_registration_count(text) to authenticated;

create index if not exists competition_applications_created_at_idx
  on public.competition_applications (created_at desc);

create index if not exists competition_application_events_application_id_idx
  on public.competition_application_events (application_id, created_at desc);

alter table public.competition_applications enable row level security;
alter table public.competition_application_events enable row level security;

drop policy if exists "Allow authenticated users to insert own competition applications" on public.competition_applications;
drop policy if exists "Allow authenticated users to read own competition applications" on public.competition_applications;
drop policy if exists "Allow authenticated users to withdraw own competition applications" on public.competition_applications;
drop policy if exists "Allow admin read competition applications" on public.competition_applications;
drop policy if exists "Allow admin update competition applications" on public.competition_applications;
drop policy if exists "Allow admin delete competition applications" on public.competition_applications;
drop policy if exists "Allow authenticated users to delete own withdrawn competition applications" on public.competition_applications;

create policy "Allow authenticated users to insert own competition applications"
on public.competition_applications
for insert
to authenticated
with check (
  owner_user_id = auth.uid()
  and nullif(trim(owner_email), '') is not null
  and nullif(trim(competition_slug), '') is not null
  and nullif(trim(competition_name), '') is not null
  and nullif(trim(stage_id), '') is not null
  and participant_kind in ('owner', 'athlete')
  and registration_kind in ('individual', 'relay', 'long-distance')
  and status = 'submitted'
);

create policy "Allow authenticated users to read own competition applications"
on public.competition_applications
for select
to authenticated
using (
  owner_user_id = auth.uid()
  or public.current_crm_role() = 'admin'
);

create policy "Allow authenticated users to withdraw own competition applications"
on public.competition_applications
for update
to authenticated
using (
  owner_user_id = auth.uid()
  and status in ('submitted', 'reviewing', 'needs_fix', 'approved', 'payment_pending')
)
with check (
  owner_user_id = auth.uid()
  and status = 'withdrawn'
);

create policy "Allow admin read competition applications"
on public.competition_applications
for select
to authenticated
using (public.current_crm_role() = 'admin');

create policy "Allow admin update competition applications"
on public.competition_applications
for update
to authenticated
using (public.current_crm_role() = 'admin')
with check (public.current_crm_role() = 'admin');

create policy "Allow admin delete competition applications"
on public.competition_applications
for delete
to authenticated
using (public.current_crm_role() = 'admin');

create policy "Allow authenticated users to delete own withdrawn competition applications"
on public.competition_applications
for delete
to authenticated
using (
  owner_user_id = auth.uid()
  and status = 'withdrawn'
);

drop policy if exists "Allow authenticated users to read own competition application events" on public.competition_application_events;
drop policy if exists "Allow admin read competition application events" on public.competition_application_events;

create policy "Allow authenticated users to read own competition application events"
on public.competition_application_events
for select
to authenticated
using (
  exists (
    select 1
    from public.competition_applications as competition_applications
    where competition_applications.id = competition_application_events.application_id
      and competition_applications.owner_user_id = auth.uid()
  )
  or public.current_crm_role() = 'admin'
);

create policy "Allow admin read competition application events"
on public.competition_application_events
for select
to authenticated
using (public.current_crm_role() = 'admin');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'competition_applications'
  ) then
    alter publication supabase_realtime add table public.competition_applications;
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'competition_application_events'
  ) then
    alter publication supabase_realtime add table public.competition_application_events;
  end if;
end;
$$;
