create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  phone text not null,
  phone_normalized text,
  consultation_date date not null,
  consultation_time time not null,
  callback_date date,
  callback_time time,
  comment text,
  status text not null default 'new',
  created_at timestamptz not null default timezone('utc', now()),
  constraint consultation_requests_status_check
    check (
      status in (
        'new',
        'processed',
        'call_back',
        'busy',
        'unavailable',
        'scheduled',
        'closed'
      )
    )
);

alter table public.consultation_requests
  add column if not exists phone_normalized text;

alter table public.consultation_requests enable row level security;

drop policy if exists "Allow public insert consultation requests" on public.consultation_requests;
drop policy if exists "Allow authenticated read consultation requests" on public.consultation_requests;
drop policy if exists "Allow admin read consultation requests" on public.consultation_requests;
drop policy if exists "Allow admin update consultation requests" on public.consultation_requests;
drop policy if exists "Allow admin delete consultation requests" on public.consultation_requests;
drop policy if exists "Allow admin insert consultation requests" on public.consultation_requests;

alter table public.consultation_requests
  alter column consultation_time type time
  using consultation_time::time;

alter table public.consultation_requests
  add column if not exists callback_date date;

alter table public.consultation_requests
  add column if not exists callback_time time;

alter table public.consultation_requests
  add column if not exists comment text;

alter table public.consultation_requests
  drop constraint if exists consultation_requests_status_check;

update public.consultation_requests
set status = 'processed'
where status = 'contacted';

alter table public.consultation_requests
  add constraint consultation_requests_status_check
  check (
    status in (
      'new',
      'processed',
      'call_back',
      'busy',
      'unavailable',
      'scheduled',
      'closed'
    )
  );

create or replace function public.normalize_phone(input_phone text)
returns text
language sql
set search_path = public
immutable
as $$
  select regexp_replace(coalesce(input_phone, ''), '\D', '', 'g');
$$;

create or replace function public.prepare_consultation_request()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  duplicate_slot_exists boolean;
  recent_requests_count integer;
begin
  new.first_name := trim(coalesce(new.first_name, ''));
  new.last_name := trim(coalesce(new.last_name, ''));
  new.phone := trim(coalesce(new.phone, ''));
  new.phone_normalized := public.normalize_phone(new.phone);

  if new.phone_normalized = '' then
    raise exception 'Укажите корректный номер телефона.';
  end if;

  if new.consultation_date < current_date then
    raise exception 'Дата консультации не может быть в прошлом.';
  end if;

  select exists (
    select 1
    from public.consultation_requests as consultation_requests
    where consultation_requests.id <> coalesce(new.id, -1)
      and consultation_requests.phone_normalized = new.phone_normalized
      and consultation_requests.consultation_date = new.consultation_date
      and consultation_requests.consultation_time = new.consultation_time
  )
  into duplicate_slot_exists;

  if duplicate_slot_exists then
    raise exception 'Заявка на это время уже была отправлена.';
  end if;

  select count(*)
  from public.consultation_requests as consultation_requests
  where consultation_requests.phone_normalized = new.phone_normalized
    and consultation_requests.created_at >= timezone('utc', now()) - interval '15 minutes'
  into recent_requests_count;

  if recent_requests_count >= 2 then
    raise exception 'Слишком много попыток. Попробуйте отправить заявку позже.';
  end if;

  return new;
end;
$$;

drop trigger if exists consultation_requests_prepare on public.consultation_requests;
create trigger consultation_requests_prepare
before insert or update on public.consultation_requests
for each row execute procedure public.prepare_consultation_request();

update public.consultation_requests
set
  first_name = trim(coalesce(first_name, '')),
  last_name = trim(coalesce(last_name, '')),
  phone = trim(coalesce(phone, '')),
  phone_normalized = public.normalize_phone(phone);

alter table public.consultation_requests
  alter column phone_normalized set not null;

create index if not exists consultation_requests_created_at_idx
  on public.consultation_requests (created_at desc);

create index if not exists consultation_requests_phone_normalized_idx
  on public.consultation_requests (phone_normalized);

create unique index if not exists consultation_requests_unique_slot_idx
  on public.consultation_requests (phone_normalized, consultation_date, consultation_time);

create policy "Allow public insert consultation requests"
on public.consultation_requests
for insert
to anon, authenticated
with check (
  nullif(trim(first_name), '') is not null
  and nullif(trim(last_name), '') is not null
  and nullif(trim(phone), '') is not null
  and char_length(public.normalize_phone(phone)) between 10 and 15
  and consultation_date >= current_date
  and consultation_time is not null
  and status = 'new'
);

create policy "Allow admin insert consultation requests"
on public.consultation_requests
for insert
to authenticated
with check (public.current_crm_role() = 'admin');

create policy "Allow admin read consultation requests"
on public.consultation_requests
for select
to authenticated
using (public.current_crm_role() = 'admin');

create policy "Allow admin update consultation requests"
on public.consultation_requests
for update
to authenticated
using (public.current_crm_role() = 'admin')
with check (public.current_crm_role() = 'admin');

create policy "Allow admin delete consultation requests"
on public.consultation_requests
for delete
to authenticated
using (public.current_crm_role() = 'admin');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'consultation_requests'
  ) then
    alter publication supabase_realtime add table public.consultation_requests;
  end if;
end;
$$;
