create table if not exists public.trainer_bookings (
  id bigint generated by default as identity primary key,
  trainer_id text not null,
  trainer_name text not null,
  client_user_id uuid references auth.users (id) on delete set null,
  client_first_name text not null,
  client_last_name text not null,
  client_phone text not null,
  client_phone_normalized text,
  client_email text not null,
  client_email_normalized text,
  preferred_date date not null,
  preferred_time time not null,
  training_format text not null default 'individual',
  comment text,
  status text not null default 'new',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint trainer_bookings_status_check
    check (status in ('new', 'contacted', 'confirmed', 'cancelled', 'completed')),
  constraint trainer_bookings_format_check
    check (training_format in ('individual', 'group'))
);

alter table public.trainer_bookings
  add column if not exists client_user_id uuid references auth.users (id) on delete set null;

alter table public.trainer_bookings
  add column if not exists client_phone_normalized text;

alter table public.trainer_bookings
  add column if not exists client_email_normalized text;

alter table public.trainer_bookings
  add column if not exists updated_at timestamptz;

update public.trainer_bookings
set updated_at = coalesce(updated_at, created_at, timezone('utc', now()))
where updated_at is null;

alter table public.trainer_bookings
  alter column updated_at set default timezone('utc', now());

alter table public.trainer_bookings
  alter column updated_at set not null;

alter table public.trainer_bookings enable row level security;

drop policy if exists "Allow public insert trainer bookings" on public.trainer_bookings;
drop policy if exists "Allow authenticated own read trainer bookings" on public.trainer_bookings;
drop policy if exists "Allow admin read trainer bookings" on public.trainer_bookings;
drop policy if exists "Allow admin update trainer bookings" on public.trainer_bookings;
drop policy if exists "Allow admin delete trainer bookings" on public.trainer_bookings;
drop policy if exists "Allow admin insert trainer bookings" on public.trainer_bookings;
drop policy if exists "Allow selected trainer read trainer bookings" on public.trainer_bookings;
drop policy if exists "Allow selected trainer update trainer booking status" on public.trainer_bookings;

alter table public.trainer_bookings
  alter column preferred_time type time
  using preferred_time::time;

alter table public.trainer_bookings
  drop constraint if exists trainer_bookings_status_check;

alter table public.trainer_bookings
  add constraint trainer_bookings_status_check
  check (status in ('new', 'in_work', 'processed', 'contacted', 'confirmed', 'cancelled', 'completed'));

alter table public.trainer_bookings
  drop constraint if exists trainer_bookings_format_check;

alter table public.trainer_bookings
  add constraint trainer_bookings_format_check
  check (training_format in ('individual', 'group'));

create or replace function public.normalize_email(input_email text)
returns text
language sql
set search_path = public
immutable
as $$
  select lower(trim(coalesce(input_email, '')));
$$;

create or replace function public.touch_trainer_booking_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

create or replace function public.prepare_trainer_booking()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  duplicate_slot_exists boolean;
begin
  new.trainer_id := trim(coalesce(new.trainer_id, ''));
  new.trainer_name := trim(coalesce(new.trainer_name, ''));
  new.client_first_name := trim(coalesce(new.client_first_name, ''));
  new.client_last_name := trim(coalesce(new.client_last_name, ''));
  new.client_phone := trim(coalesce(new.client_phone, ''));
  new.client_email := trim(coalesce(new.client_email, ''));
  new.comment := nullif(trim(coalesce(new.comment, '')), '');
  new.client_phone_normalized := public.normalize_phone(new.client_phone);
  new.client_email_normalized := public.normalize_email(new.client_email);

  if new.trainer_id = '' or new.trainer_name = '' then
    raise exception 'Не удалось определить тренера для записи.';
  end if;

  if new.client_first_name = '' or new.client_last_name = '' then
    raise exception 'Укажите имя и фамилию.';
  end if;

  if new.client_phone_normalized = '' then
    raise exception 'Укажите корректный номер телефона.';
  end if;

  if new.client_email_normalized = '' then
    raise exception 'Укажите корректную электронную почту.';
  end if;

  if
    new.preferred_date < current_date
    and (
      TG_OP = 'INSERT'
      or new.preferred_date is distinct from old.preferred_date
    )
  then
    raise exception 'Дата записи не может быть в прошлом.';
  end if;

  select exists (
    select 1
    from public.trainer_bookings as trainer_bookings
    where trainer_bookings.id <> coalesce(new.id, -1)
      and trainer_bookings.trainer_id = new.trainer_id
      and trainer_bookings.client_phone_normalized = new.client_phone_normalized
      and trainer_bookings.preferred_date = new.preferred_date
      and trainer_bookings.preferred_time = new.preferred_time
  )
  into duplicate_slot_exists;

  if duplicate_slot_exists then
    raise exception 'Запись к этому тренеру на выбранные дату и время уже существует.';
  end if;

  return new;
end;
$$;

drop trigger if exists trainer_bookings_prepare on public.trainer_bookings;
create trigger trainer_bookings_prepare
before insert or update on public.trainer_bookings
for each row execute procedure public.prepare_trainer_booking();

drop trigger if exists trainer_bookings_touch_updated_at on public.trainer_bookings;
create trigger trainer_bookings_touch_updated_at
before update on public.trainer_bookings
for each row execute procedure public.touch_trainer_booking_updated_at();

update public.trainer_bookings
set
  trainer_id = trim(coalesce(trainer_id, '')),
  trainer_name = trim(coalesce(trainer_name, '')),
  client_first_name = trim(coalesce(client_first_name, '')),
  client_last_name = trim(coalesce(client_last_name, '')),
  client_phone = trim(coalesce(client_phone, '')),
  client_phone_normalized = public.normalize_phone(client_phone),
  client_email = trim(coalesce(client_email, '')),
  client_email_normalized = public.normalize_email(client_email),
  comment = nullif(trim(coalesce(comment, '')), '');

alter table public.trainer_bookings
  alter column client_phone_normalized set not null;

alter table public.trainer_bookings
  alter column client_email_normalized set not null;

create index if not exists trainer_bookings_created_at_idx
  on public.trainer_bookings (created_at desc);

create index if not exists trainer_bookings_updated_at_idx
  on public.trainer_bookings (updated_at desc);

create index if not exists trainer_bookings_client_email_normalized_idx
  on public.trainer_bookings (client_email_normalized);

create index if not exists trainer_bookings_client_user_id_idx
  on public.trainer_bookings (client_user_id);

create or replace function public.current_crm_email()
returns text
language sql
stable
set search_path = public
as $$
  select lower(trim(coalesce(auth.jwt() ->> 'email', '')));
$$;

grant execute on function public.current_crm_email() to authenticated;
revoke execute on function public.current_crm_email() from public, anon;

create policy "Allow public insert trainer bookings"
on public.trainer_bookings
for insert
to anon, authenticated
with check (
  nullif(trim(trainer_id), '') is not null
  and nullif(trim(trainer_name), '') is not null
  and nullif(trim(client_first_name), '') is not null
  and nullif(trim(client_last_name), '') is not null
  and nullif(trim(client_phone), '') is not null
  and char_length(public.normalize_phone(client_phone)) between 10 and 15
  and nullif(trim(client_email), '') is not null
  and preferred_date >= current_date
  and preferred_time is not null
  and training_format in ('individual', 'group')
  and status = 'new'
);

create policy "Allow admin insert trainer bookings"
on public.trainer_bookings
for insert
to authenticated
with check (public.current_crm_role() = 'admin');

create policy "Allow authenticated own read trainer bookings"
on public.trainer_bookings
for select
to authenticated
using (
  public.current_crm_role() = 'admin'
  or auth.uid() = client_user_id
  or public.normalize_email(auth.jwt() ->> 'email') = client_email_normalized
);

create policy "Allow selected trainer read trainer bookings"
on public.trainer_bookings
for select
to authenticated
using (
  public.current_crm_role() = 'trainer'
  and exists (
    select 1
    from public.crm_users as crm_user
    where crm_user.id = auth.uid()
      and crm_user.role = 'trainer'
      and (
        public.current_crm_email() = public.normalize_email(trainer_bookings.trainer_id)
        or trim(coalesce(crm_user.name, '')) = trainer_bookings.trainer_name
      )
  )
);

create policy "Allow admin read trainer bookings"
on public.trainer_bookings
for select
to authenticated
using (public.current_crm_role() = 'admin');

create policy "Allow admin update trainer bookings"
on public.trainer_bookings
for update
to authenticated
using (public.current_crm_role() = 'admin')
with check (public.current_crm_role() = 'admin');

create policy "Allow selected trainer update trainer booking status"
on public.trainer_bookings
for update
to authenticated
using (
  public.current_crm_role() = 'trainer'
  and exists (
    select 1
    from public.crm_users as crm_user
    where crm_user.id = auth.uid()
      and crm_user.role = 'trainer'
      and (
        public.current_crm_email() = public.normalize_email(trainer_bookings.trainer_id)
        or trim(coalesce(crm_user.name, '')) = trainer_bookings.trainer_name
      )
  )
)
with check (
  public.current_crm_role() = 'trainer'
  and status in ('new', 'in_work', 'processed', 'contacted', 'confirmed', 'cancelled', 'completed')
  and exists (
    select 1
    from public.crm_users as crm_user
    where crm_user.id = auth.uid()
      and crm_user.role = 'trainer'
      and (
        public.current_crm_email() = public.normalize_email(trainer_bookings.trainer_id)
        or trim(coalesce(crm_user.name, '')) = trainer_bookings.trainer_name
      )
  )
);

create policy "Allow admin delete trainer bookings"
on public.trainer_bookings
for delete
to authenticated
using (public.current_crm_role() = 'admin');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'trainer_bookings'
  ) then
    alter publication supabase_realtime add table public.trainer_bookings;
  end if;
end;
$$;
