export const trainersHeroStats = [
  {
    value: '6 тренеров',
    label: 'под разные задачи и возраст',
  },
  {
    value: 'Индивидуальный подход',
    label: 'подбираем темп, формат и цели',
  },
  {
    value: 'От новичка до старта',
    label: 'работаем на технику, уверенность и результат',
  },
]

export const trainers = [
  {
    id: 'maksim-belyaev',
    name: 'Максим Андреевич Беляев',
    primaryProfile: 'Подготовка к соревнованиям, мини-группа, спортивная школа',
    availableSlots: '2 места',
    education: ['Образование высшее', 'СибГУФК'],
    achievements: 'Заслуженный тренер России, МС',
    experience: '11 лет',
    audience: 'Спортсмены',
    minimumAge: '17 лет',
    level: 'Подготовка к соревнованиям, индивидуальные тренировки, групповые тренировки',
    metro: 'Сокол, Аэропорт',
    email: 'belyaev@smartswim.ru',
    phone: '+7 916 729-07-73',
    phoneHref: 'tel:+79167290773',
  },
  {
    id: 'anna-krylova',
    name: 'Анна Сергеевна Крылова',
    primaryProfile: 'Начинающие, адаптация к воде, индивидуальные занятия',
    availableSlots: '3 места',
    education: ['Образование высшее', 'РГУФКСМиТ'],
    achievements: 'КМС, призер всероссийских стартов',
    experience: '8 лет',
    audience: 'Дети и взрослые',
    minimumAge: '6 лет',
    level: 'Начинающий, индивидуальные тренировки, групповые тренировки',
    metro: 'Проспект Мира, Рижская',
    email: 'krylova@smartswim.ru',
    phone: '+7 926 410-22-18',
    phoneHref: 'tel:+79264102218',
  },
  {
    id: 'dmitriy-sokolov',
    name: 'Дмитрий Олегович Соколов',
    primaryProfile: 'Соревнования, открытая вода, стартовые серии',
    availableSlots: '1 место',
    education: ['Образование высшее', 'МГАФК'],
    achievements: 'МС, финалист чемпионатов России',
    experience: '13 лет',
    audience: 'Спортсмены и любители стартов',
    minimumAge: '15 лет',
    level: 'Подготовка к соревнованиям, открытая вода, индивидуальные тренировки',
    metro: 'Динамо, Петровский парк',
    email: 'sokolov@smartswim.ru',
    phone: '+7 903 155-48-22',
    phoneHref: 'tel:+79031554822',
  },
  {
    id: 'elena-morozova',
    name: 'Елена Викторовна Морозова',
    primaryProfile: 'Техника, восстановление, плавание для взрослых',
    availableSlots: '4 места',
    education: ['Образование высшее', 'НГУ им. П. Ф. Лесгафта'],
    achievements: 'КМС, судья II категории',
    experience: '10 лет',
    audience: 'Взрослые любители',
    minimumAge: '18 лет',
    level: 'Начинающий, индивидуальные тренировки, групповые тренировки',
    metro: 'Белорусская, Маяковская',
    email: 'morozova@smartswim.ru',
    phone: '+7 915 233-60-14',
    phoneHref: 'tel:+79152336014',
  },
  {
    id: 'kirill-gromov',
    name: 'Кирилл Денисович Громов',
    primaryProfile: 'Выносливость, ОФП, комплексная подготовка',
    availableSlots: '2 места',
    education: ['Образование высшее', 'РГУ нефти и газа, кафедра физвоспитания'],
    achievements: 'КМС, участник заплывов на открытой воде',
    experience: '9 лет',
    audience: 'Подростки и взрослые',
    minimumAge: '14 лет',
    level: 'Открытая вода, групповые тренировки, подготовка к соревнованиям',
    metro: 'Щукинская, Стрешнево',
    email: 'gromov@smartswim.ru',
    phone: '+7 977 300-11-45',
    phoneHref: 'tel:+79773001145',
  },
  {
    id: 'sofiya-zhukova',
    name: 'София Алексеевна Жукова',
    primaryProfile: 'Персональные планы, взрослые, цели под запрос',
    availableSlots: '3 места',
    education: ['Образование высшее', 'РАНХиГС + профпереподготовка по плаванию'],
    achievements: 'КМС, сертификат тренера по open water',
    experience: '7 лет',
    audience: 'Взрослые и корпоративные группы',
    minimumAge: '16 лет',
    level: 'Начинающий, открытая вода, индивидуальные тренировки, групповые тренировки',
    metro: 'Павелецкая, Серпуховская',
    email: 'zhukova@smartswim.ru',
    phone: '+7 985 410-09-67',
    phoneHref: 'tel:+79854100967',
  },
]
