import { formatRussianPhone, toRussianPhoneHref } from '@/utils/phone'

export const trainerMetroFilterOptions = [
  'Аэропорт',
  'Белорусская',
  'Динамо',
  'Маяковская',
  'Павелецкая',
  'Петровский парк',
  'Проспект Мира',
  'Рижская',
  'Серпуховская',
  'Сокол',
  'Стрешнево',
  'Щукинская',
]

export const trainerPreparationLevelFilterOptions = [
  'Начинающий',
  'Подготовка к соревнованиям',
  'Открытая вода',
  'Индивидуальные тренировки',
  'Групповые тренировки',
]

export const trainerAgeGroupFilterOptions = ['0-3 года', '4-6 лет', '7-17 лет', '18+']

export const trainersHeroStats = [
  {
    value: '6 тренеров',
    label: 'под разные задачи и возраст',
  },
  {
    value: 'Индивидуальный подход',
    label: 'подбираем темп, формат и цели',
  },
  {
    value: 'От новичка до старта',
    label: 'работаем на технику, уверенность и результат',
  },
]

export const trainers = [
  {
    id: 'maksim-belyaev',
    name: 'Максим Андреевич Беляев',
    primaryProfile: 'Подготовка к соревнованиям, мини-группа, спортивная школа',
    availableSlots: '2 места',
    education: ['Образование высшее', 'СибГУФК'],
    achievements: 'Заслуженный тренер России, МС',
    experience: '11 лет',
    audience: 'Спортсмены',
    minimumAge: '17 лет',
    level: 'Подготовка к соревнованиям, индивидуальные тренировки, групповые тренировки',
    metro: 'Сокол, Аэропорт',
    metroStations: ['Сокол', 'Аэропорт'],
    preparationLevels: ['Подготовка к соревнованиям', 'Индивидуальные тренировки', 'Групповые тренировки'],
    ageGroups: ['7-17 лет', '18+'],
    email: 'belyaev@smartswim.ru',
    phone: formatRussianPhone('+7 916 729-07-73'),
    phoneHref: toRussianPhoneHref('+7 916 729-07-73'),
  },
  {
    id: 'anna-krylova',
    name: 'Анна Сергеевна Крылова',
    primaryProfile: 'Начинающие, адаптация к воде, индивидуальные занятия',
    availableSlots: '3 места',
    education: ['Образование высшее', 'РГУФКСМиТ'],
    achievements: 'КМС, призер всероссийских стартов',
    experience: '8 лет',
    audience: 'Дети и взрослые',
    minimumAge: '6 лет',
    level: 'Начинающий, индивидуальные тренировки, групповые тренировки',
    metro: 'Проспект Мира, Рижская',
    metroStations: ['Проспект Мира', 'Рижская'],
    preparationLevels: ['Начинающий', 'Индивидуальные тренировки', 'Групповые тренировки'],
    ageGroups: ['0-3 года', '4-6 лет', '7-17 лет'],
    email: 'krylova@smartswim.ru',
    phone: formatRussianPhone('+7 926 410-22-18'),
    phoneHref: toRussianPhoneHref('+7 926 410-22-18'),
  },
  {
    id: 'dmitriy-sokolov',
    name: 'Дмитрий Олегович Соколов',
    primaryProfile: 'Соревнования, открытая вода, стартовые серии',
    availableSlots: '1 место',
    education: ['Образование высшее', 'МГАФК'],
    achievements: 'МС, финалист чемпионатов России',
    experience: '13 лет',
    audience: 'Спортсмены и любители стартов',
    minimumAge: '15 лет',
    level: 'Подготовка к соревнованиям, открытая вода, индивидуальные тренировки',
    metro: 'Динамо, Петровский парк',
    metroStations: ['Динамо', 'Петровский парк'],
    preparationLevels: ['Подготовка к соревнованиям', 'Открытая вода', 'Индивидуальные тренировки'],
    ageGroups: ['7-17 лет', '18+'],
    email: 'sokolov@smartswim.ru',
    phone: formatRussianPhone('+7 903 155-48-22'),
    phoneHref: toRussianPhoneHref('+7 903 155-48-22'),
  },
  {
    id: 'elena-morozova',
    name: 'Елена Викторовна Морозова',
    primaryProfile: 'Техника, восстановление, плавание для взрослых',
    availableSlots: '4 места',
    education: ['Образование высшее', 'НГУ им. П. Ф. Лесгафта'],
    achievements: 'КМС, судья II категории',
    experience: '10 лет',
    audience: 'Взрослые любители',
    minimumAge: '18 лет',
    level: 'Начинающий, индивидуальные тренировки, групповые тренировки',
    metro: 'Белорусская, Маяковская',
    metroStations: ['Белорусская', 'Маяковская'],
    preparationLevels: ['Начинающий', 'Индивидуальные тренировки', 'Групповые тренировки'],
    ageGroups: ['18+'],
    email: 'morozova@smartswim.ru',
    phone: formatRussianPhone('+7 915 233-60-14'),
    phoneHref: toRussianPhoneHref('+7 915 233-60-14'),
  },
  {
    id: 'kirill-gromov',
    name: 'Кирилл Денисович Громов',
    primaryProfile: 'Выносливость, ОФП, комплексная подготовка',
    availableSlots: '2 места',
    education: ['Образование высшее', 'РГУ нефти и газа, кафедра физвоспитания'],
    achievements: 'КМС, участник заплывов на открытой воде',
    experience: '9 лет',
    audience: 'Подростки и взрослые',
    minimumAge: '14 лет',
    level: 'Открытая вода, групповые тренировки, подготовка к соревнованиям',
    metro: 'Щукинская, Стрешнево',
    metroStations: ['Щукинская', 'Стрешнево'],
    preparationLevels: ['Подготовка к соревнованиям', 'Открытая вода', 'Групповые тренировки'],
    ageGroups: ['7-17 лет', '18+'],
    email: 'gromov@smartswim.ru',
    phone: formatRussianPhone('+7 977 300-11-45'),
    phoneHref: toRussianPhoneHref('+7 977 300-11-45'),
  },
  {
    id: 'sofiya-zhukova',
    name: 'София Алексеевна Жукова',
    primaryProfile: 'Персональные планы, взрослые, цели под запрос',
    availableSlots: '3 места',
    education: ['Образование высшее', 'РАНХиГС + профпереподготовка по плаванию'],
    achievements: 'КМС, сертификат тренера по open water',
    experience: '7 лет',
    audience: 'Взрослые и корпоративные группы',
    minimumAge: '16 лет',
    level: 'Начинающий, открытая вода, индивидуальные тренировки, групповые тренировки',
    metro: 'Павелецкая, Серпуховская',
    metroStations: ['Павелецкая', 'Серпуховская'],
    preparationLevels: ['Начинающий', 'Открытая вода', 'Индивидуальные тренировки', 'Групповые тренировки'],
    ageGroups: ['18+'],
    email: 'zhukova@smartswim.ru',
    phone: formatRussianPhone('+7 985 410-09-67'),
    phoneHref: toRussianPhoneHref('+7 985 410-09-67'),
  },
]
